AE-445 tornado cash updates
arbitraryexecution/forta-tornado-cash pull request #2
Opened 2021-10-15 22:11 UTC by rossAE

TODO:
    break addressees out into json
    make a negative test and maybe change the test structure
    add more info into metadata like eth withdraw size
    use ethers for decoding of the events

2021-10-18 15:38 UTC, arbitrary-echo commented on package.json
> +    "forta-agent": "^0.0.18"
Is there a ticket for updating this to `0.0.21`?

2021-10-18 15:58 UTC, y0wl commented on package.json
> +    "forta-agent": "^0.0.18"
.18 -> .21 should be trivial

2021-10-18 19:30 UTC, arbitrary-echo commented on src/agent.js
> +  if (parsedLogs.length !== 0) {
Is it possible to have more than one entry in the `parsedLogs` Array?

If so, should the code inside this conditional perform a `forEach`?
If not, should this conditional be changed to `=== 1`?

2021-10-18 20:15 UTC, arbitrary-echo requested changes
Just one comment about the number of logs that may be present within a transaction.

2021-10-19 00:17 UTC, rossAE commented on package.json
> +    "forta-agent": "^0.0.18"
done

2021-10-19 00:18 UTC, rossAE commented on src/agent.js
> +  if (parsedLogs.length !== 0) {
good point. if withdraw is called from a contract, it could be wrapped in some function that calls it multiple times in one transaction, in which case multiple withdrawal events would be emitted. i have included a forEach as you advised in my latest commit.

2021-10-19 09:52 UTC, echoAE approved these changes

2021-10-20 22:10 UTC, arbitrary-kdawg approved these changes

2021-10-20 22:14 UTC, merged